### ISSUE TITLE
Permission Denied when creating a backup job

### ISSUE THREAD

**Issue by crane-denny** [dumrauf/qnap_glacier_iam_user#4]
Hello! :)

Thanks for sharing this. I am getting really annoyed by the lack of documentation here from QNAP what is needed and what not...

I created the policy document like you described. But when I try to create a backup job from within HSB 3 I am getting a "Cannot upload to the cloud service. Permission denied." error.

Do you have maybe a clue?

**Comment by crane-denny** [comment]
I can give right away the answer after pulling my hair and looking into CloudTrail. :D
HBS 3 wants to play with tags.

New policy should look like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowGlacierGlobal",
            "Effect": "Allow",
            "Action": [
                "glacier:ListVaults",
                "glacier:GetDataRetrievalPolicy"
            ],
            "Resource": "*"
        },
        {
            "Sid": "AllowGlacierRessource",
            "Effect": "Allow",
            "Action": [
                "glacier:UploadMultipartPart",
                "glacier:UploadArchive",
                "glacier:ListTagsForVault",
                "glacier:ListParts",
                "glacier:ListMultipartUploads",
                "glacier:ListJobs",
                "glacier:InitiateMultipartUpload",
                "glacier:InitiateJob",
                "glacier:GetVaultNotifications",
                "glacier:GetVaultLock",
                "glacier:GetVaultAccessPolicy",
                "glacier:GetJobOutput",
                "glacier:DescribeVault",
                "glacier:DescribeJob",
                "glacier:DeleteArchive",
                "glacier:CreateVault",
                "glacier:CompleteMultipartUpload",
                "glacier:AbortMultipartUpload",
                "glacier:RemoveTagsFromVault",
                "glacier:AddTagsToVault"
            ],
            "Resource": "<your-arn>"
        }
    ]
}
```

**Comment by dumrauf** [comment]
Hi @crane-denny,

Many thanks for creating the ticket!

Even more so for providing the solution to the problem and improving things for everyone - much, much appreciated!

I hope you don't mind me updating the [original article](https://www.how-hard-can-it.be/qnap-glacier-iam-user/?utm_source=GitHub&utm_medium=social&utm_campaign=Issue) and giving credit where credit is due.

Keep up the great work!

Thanks,
 Dominic

**Comment by crane-denny** [comment]
Sure thing. It's an alias anyways. ^^'
